[package]
name = "async_serde"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.138"
tokio = {version = "1.43.0", features = ["full"]}
json5 ={ version = "0.4.1", optional = true}


[dev-dependencies]
tokio = { version = "1.43.0", features = ["full", "test-util"] }

[features]
relaxed = ["json5"]